name: Regenerate corpus

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version to fetch (branch, tag, or Go ogen module version)'
        required: true
        default: 'main'
      filter:
        type: string
        description: 'Additional query filter'
        required: false
      yaml:
        type: boolean
        description: 'Query YAML schemas'
        required: false
        default: true

permissions:
  contents: write
  pull-requests: write

jobs:
  regenerate-corpus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.18"
          check-latest: true
          cache: true

      - name: Generate files
        id: generate
        env:
          GOPROXY: direct
          COLLECTOR_FLAGS: >-
            --yaml=${{ github.event.inputs.yaml }}
            --filter=${{ github.event.inputs.filter }}
          VERSION: ${{ github.event.inputs.version }}
        run: |
          make generate
          rm -r ./corpus/notImplemented
          rm -r ./corpus/good

          echo "Re-generate corpus." >> summary.txt
          echo "" >> summary.txt
          echo "\`\`\`diff" >> summary.txt
          cat stats.txt >> summary.txt
          echo "\`\`\`" >> summary.txt

          cat summary.txt >> $GITHUB_STEP_SUMMARY

          SUMMARY="$(cat summary.txt)"
          SUMMARY="${SUMMARY//'%'/'%25'}"
          SUMMARY="${SUMMARY//$'\n'/'%0A'}"
          SUMMARY="${SUMMARY//$'\r'/'%0D'}"
          echo "::set-output name=summary::$SUMMARY"

      - name: Upload profiles
        uses: actions/upload-artifact@v3
        with:
          path: "*profile.out"
          if-no-files-found: error
          retention-days: 1

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          author: GitHub <actions@github.com>
          committer: GitHub <actions@github.com>
          commit-message: 'chore: regenerate corpus'
          branch: chore/regenerate-corpus
          delete-branch: true
          add-paths: |
            ./stats.txt
            ./corpus
          title: Re-generate corpus
          assignees: ${{ github.event.sender.login || 'tdakkota' }}
          reviewers: ${{ github.event.sender.login || 'tdakkota' }}
          body: |
            ${{ steps.generate.outputs.summary }}
