name: Regenerate corpus

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version to fetch (branch, tag, or Go ogen module version)'
        required: true
        default: 'main'
      filter:
        type: string
        description: 'Additional query filter'
        required: false
      yaml:
        type: boolean
        description: 'Query YAML schemas'
        required: false
        default: true
      query:
        type: string
        description: 'Query to use'
        required: false
        default: ''
      send-pr:
        type: boolean
        description: 'Send PR with generated corpus'
        required: false
        default: true

permissions:
  contents: write
  pull-requests: write

jobs:
  regenerate-corpus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: regenerate-corpus-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            regenerate-corpus-${{ runner.os }}-go-

      - name: Generate files
        id: generate
        env:
          GOPROXY: direct
          COLLECTOR_FLAGS: >-
            --yaml=${{ github.event.inputs.yaml }}
            --query=${{ github.event.inputs.query }}
            --filter=${{ github.event.inputs.filter }}
          VERSION: ${{ github.event.inputs.version }}
        run: |
          make generate
          STATS="$(cat stats.txt)"
          STATS="${STATS//'%'/'%25'}"
          STATS="${STATS//$'\n'/'%0A'}"
          STATS="${STATS//$'\r'/'%0D'}"
          echo "::set-output name=stats::$STATS"
          rm -r ./corpus/notImplemented
          rm -r ./corpus/good

      - name: Upload profiles
        uses: actions/upload-artifact@v3
        with:
          path: "*profile.out"
          if-no-files-found: error
          retention-days: 1

      - name: Create PR
        if: ${{ github.event.inputs.send-pr }}
        uses: peter-evans/create-pull-request@v4
        with:
          author: GitHub <actions@github.com>
          committer: GitHub <actions@github.com>
          commit-message: 'chore: regenerate corpus'
          branch: chore/regenerate-corpus
          delete-branch: true
          add-paths: |
            ./stats.txt
            ./corpus
          title: Re-generate corpus
          assignees: ${{ github.event.sender.login || 'tdakkota' }}
          reviewers: ${{ github.event.sender.login || 'tdakkota' }}
          body: |
            Re-generate corpus.
            ```diff
            ${{ steps.generate.outputs.stats }}
            ```
