name: Regenerate corpus

on:
  workflow_dispatch:

jobs:
  regenerate-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v2.1.7
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: update-corpus-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            update-corpus-${{ runner.os }}-go-

      - name: Generate files
        id: generate
        env:
          GOPROXY: direct
        run: |
          make generate
          STATS="$(cat stats.txt)"
          STATS="${STATS//'%'/'%25'}"
          STATS="${STATS//$'\n'/'%0A'}"
          STATS="${STATS//$'\r'/'%0D'}"
          echo "::set-output name=stats::$STATS"

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          author: GitHub <actions@github.com>
          committer: GitHub <actions@github.com>
          commit-message: 'chore: regenerate corpus'
          branch: chore/regenerate-corpus
          delete-branch: true
          add-paths: |
             ./stats.txt
             ./corpus
          title: Re-generate corpus
          body: |
            Re-generate corpus.
            ```diff
            ${{ steps.generate.outputs.stats }}
            ```
